language: java
jdk:
  - openjdk8

dist: xenial

cache:
  directories:
    - $HOME/.m2

install:
 - sudo pip install wheel ansible pycrypto
 - sudo add-apt-repository universe
 - sudo apt-get update
 - git clone https://github.com/icatproject-contrib/icat-ansible.git
 - echo -e "[icat-server-dev-hosts]\nlocalhost ansible_connection=local" > hosts
 - echo -e $ANSIBLE_VAULT_PASSWORD > vault_pass.txt
 - mv vault.yml icat-ansible/group_vars/all
 - 'sed -i -e "s/^payara_user: ''glassfish''/payara_user: ''travis''/" icat-ansible/group_vars/all/vars.yml'
 - ansible-playbook --vault-password-file ./vault_pass.txt --inventory ./hosts icat-ansible/icat-server-dev-hosts.yml

before_script:
 - grep payara ~/.bash_profile > payara_path_command
 - source payara_path_command
 - HOSTNAME=$(hostname)
 - 'sed -i -e "s/localhost\.localdomain/${HOSTNAME}/" src/main/resources/run.properties'
 - ICAT_SERVER_VERSION=$(grep 'icat_server=[0-9].[0-9].[0-9]' /etc/ansible/facts.d/local.fact | grep -o '[0-9].[0-9].[0-9]')
 - asadmin undeploy icat.server-$ICAT_SERVER_VERSION

script:
 - mvn install -B

after_failure:
 - cat /home/travis/logs/lucene.log
 - cat /home/travis/logs/icat.log
 - cat /home/travis/payara*/glassfish/domains/domain1/logs/server.log

